### ISSUE TITLE
radio

### ISSUE THREAD

**Issue by ghost** [domodom/Avatar-Plugin-webradio#2]
bonjour , merci pour le nouveau plugin radio,
une question c'est normale que quand je veux changer de radio il ne se passe rien, parce que quand je veux ecouter une autre radio je suis obliger d'arreter la radio puis de nouveau passer une regle pour écouter une autre radio, cordialement

**Comment by domodom** [comment]
Je vais vérifier dans la journée, mais c'est possible. Étant donné que le lecteur est ouvert, pour changer de radio je suis obligé de fermer le lecteur avant. Je regarde cela est ferait une update dans la journée.

**Comment by halimgambit** [comment]
c'est une merveille ce plugin radio, tu as fait du beau travail du pure dev, je le garde et je jette poubelle mes 2 plug-in radio que j'ai creer , je creer des plugin scenario maison avec du cron et ca me lance le scenario avec tes plug-in, si je veux que ca lance une radio(franceinfo) sans préciser le nom de la radio que je veux, je met la radio en derniere position dans le fichier propriéte:
                                "RTL2": "rtl2",
				"EUROPE 1": "europe1",
				"NOSTALGIE": "nostalgie",
				"FRANCEINFO": "franceinfo"
			},
			"rules": {

Scenario:
setTimeout(() => {
    Avatar.speak('Voici ton signe astrologique', data.client, function(){
    Avatar.Speech.end(data.client);
    });
}, 58000);
    setTimeout(() => {
    Avatar.call('horoscope',{client:data.client,command:'recherche',sentence:'lion'},function(){});
}, 62000);
    setTimeout(() => {
    Avatar.call('webradio',{client:data.client,command:'openWebradio'}, function(){});
}, 75000);
encore merci beaucoup
une question c'est quoi le logo/icone "google"sur ton interface du serveur? cordialement
